In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('C:\\Users\\sathv\\Downloads\\data (2).csv')

In [5]:
df.head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368
7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510
8,844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720
9,84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750

here all the columns are considered as x variables and diagnosis column is considered as y variable which the predicting variable and the irrelevent column is id there is no use of id
M - Cancer ; B - non-Cancer

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

so far from the info seen we dont have any null values if there are any null values fillna, dropna try these check with EDA Project.

In [7]:
len(df)

569

totally we have 569 records

In [8]:
df.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

here we are checking the value and its count

we have seen counts of the values now lets calculate the percentage of the values so non - cancer - 62% and cancer - 37%

In [9]:
df.diagnosis.value_counts()/len(df)*100

diagnosis
B    62.741652
M    37.258348
Name: count, dtype: float64

so now as we checked all the data splitting of data we need to divide the data into train and test data ####splitting the data into x and y###

In [10]:
#splitting the data into training and testing data
x = df.drop(["id", "diagnosis"], axis=1)

as we have seen all the data is x values except id and diagnosis we just dropped the columns id and diagnosis , axis=1(represents row wise data) here in row wise the columns will be deducted from the data

In [11]:
x

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [12]:
y = df.diagnosis.values

lets start with the train and test split as we have segregated the x and y values so here the training data will be trained to the model and testing will be tested by the trained model

In [15]:
#Train & Test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [19]:
len(x_train)

426

In [20]:
len(x_test)

143

here this is a sklearn library if not available need to install the library 
pip install scikit_learn --a ML Library -- to split the test and train data from sklearn.model_selection import train_test_split we used it.
in this we used x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25) the test_size = 0.25 - it splits the data in 75:25 ratio 25% the test data

Feature Scaling - 2 types - Normalization(mean-max scaler) and Standardization(Standard scaler)

In [23]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

fit_transform - used in training data 
- Fit → learns the parameters from the training set (for example, a scaler learns the mean and standard deviation).
- Transform → applies those parameters to scale the training data.

transform - used on test data
- It doesn’t learn anything new; it simply applies the parameters that were already learned from the training set. This ensures consistency and prevents data leakage.

In [24]:
x_train_sc

array([[-0.27228964,  0.59049678, -0.2697897 , ...,  0.72655196,
         1.25536605,  0.6721354 ],
       [-0.47881267, -0.79266252, -0.3886375 , ...,  0.93087389,
         1.71264079,  2.19938288],
       [ 1.76138861,  0.86667588,  1.68932251, ...,  0.67470908,
         1.24910202, -0.00435622],
       ...,
       [-0.4874178 , -0.94207089, -0.5537734 , ..., -1.10594124,
         0.01508663, -0.8621476 ],
       [-0.32678877,  0.03361104, -0.30732059, ..., -0.22064788,
         1.10346314,  0.42751603],
       [-0.73983485, -1.07789668, -0.71890929, ..., -0.66893629,
        -0.88067074, -0.13099546]], shape=(426, 30))

In [25]:
x_test_sc

array([[-0.6279682 , -1.87700508, -0.65677483, ..., -0.67534041,
        -0.67552351, -0.60291601],
       [ 0.39317349,  0.17396435,  0.438293  , ...,  1.51029427,
         0.46296531,  0.98169796],
       [-0.42144516, -0.23351302, -0.38363339, ...,  0.42159387,
         0.53030371,  1.05746502],
       ...,
       [-0.54765369, -0.26746946, -0.56628369, ..., -0.37754882,
         0.5115116 , -0.49034781],
       [-0.87178012, -0.08410465, -0.77520562, ...,  2.12478483,
         1.97729638,  3.05988023],
       [-0.65378358, -0.11353357, -0.58213007, ...,  0.63353974,
         2.92786407,  3.05446829]], shape=(143, 30))

feature scaling is done for the training data

## MODEL BUILDING - KNN

In [29]:
 # Model Building
from sklearn.neighbors import KNeighborsClassifier
# Intiating the classifer
model_knn = KNeighborsClassifier()
# KNeighborsclassifier() - takes the default value of n_neighbors as 5, and all the different parameters as default values.we can change the default values of the parameters as per our requirement.
# we have intiated the classifer,now we will fit the model on the training data(scalerdata for x).
model_knn.fit(x_train_sc,y_train)

KNeighborsClassifier()

the classifier/model is trained with the training data
now lets check the trained model with the test data - prediction

"In supervised learning, we scale the input features 'X' because many algorithms are distance-based or sensitive to feature magnitude. Scaling ensures that no single feature dominates due to its larger numeric range. However, we don’t scale the target variable 'y' because it represents the labels we’re predicting. Scaling 'y' would change the meaning of the classes or regression targets, which would mislead the model. So the rule of thumb is: scale your features, not your labels.”

In [31]:
y_pred_knn = model_knn.predict(x_test_sc)

lets check the predicted values

In [32]:
y_pred_knn

array(['B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B',
       'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'M',
       'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M'],
      dtype=object)

In [33]:
y_test

array(['B', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B',
       'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'M',
       'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M'],
      dtype=object)

just compare the predicted values with the original values so compare the model how much of the % is predicted correctly.

In [37]:
# Classification metrics to check how the model is performing
# Accuracy score
from sklearn.metrics import accuracy_score
print(round(accuracy_score(y_test,y_pred_knn)*100,2))

97.2

normally accuracy_score gives result in decimal point so in this stage we have rounded it to 2 decimal points and *100 to get the value in % form.

## Here after the accuracy_score i have seen a difference where if i do this entire process the accuracy differs slightly like we might get value as 95% but in this case if have got 98% as the accuracy_score the thing is while performing train_test_split we have given all the parameters as default, in that one such parameter is random_state - by default it is null, if you mention a number to it like 42,49,etc., and check the accuracy and perform the task again and again the accuracy_score does not change so if you do not want any changes in the accuracy_score while performing train_test_split give the "random_state = 49" along with the required parameters in it.

In [38]:
#predict for a new patient
new_patient = [[17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189]]

here the data is given inside [[ ]] because most of the ML libraries expect the input in the form of 2D Array format 
[ ]- represent the dataset
[ ]- represent one sample's feature vector - data of a row

In [39]:
#feature scaling for the new patient data
new_data_sc = sc.transform(new_patient)
new_data_sc

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [ ]:
#predicting the class for the new patient data.
y_pred_s = model_knn.predict(new_data_sc)
y_pred_s

array(['M'], dtype=object)

the new patient is a cancer patient.

for feature Scaling - we can use normalization or standardization

- here we have took a dataset of breast cancer prediction
- we have created a classification model 
- step by step
  1. importing required libraries
  2. read the dataset
  3. checking if any null values in the dataset, if any make all the data into non null
  4. checking the % count of cancer and non cancer patients and then length of the dataset
  5. splitting the data into input features 'x' and target variable 'y'
  6. import train_test_split from sklearn 
  7. preprocessing - import standardscaler from sklearn for feature Scaling with fit_transform and transform
  8. KNN Model building - import KNeighborsClassifier from sklearn.neighbours
  9. once the model is created predict the values and compare them.
  10. Classification metrics - accuracy_score to check how much of the percentage is matching

# interview Summary:-
“In this project, I built a breast cancer prediction model using the KNN algorithm. I started by importing libraries and loading the dataset, then cleaned and explored the data to understand class distribution. After separating features and labels, I split the dataset into training and testing sets. I applied feature scaling with StandardScaler to ensure all features were on the same scale. Next, I trained a KNN classifier on the training data, made predictions on the test set, and evaluated the model using accuracy and classification metrics. This workflow demonstrates a complete end-to-end machine learning pipeline — from raw data to model evaluation.”